packages:
  - apps/*
  - packages/*
  - infrastructure/*
  - scripts/*

catalog:
  '@prisma/client': ^5.22.0
  concurrently: ^9.2.1
  dotenv: ^16.6.1
  eslint: ^9.39.1
  next: ^14.2.33
  prettier: ^3.6.2
  prisma: ^5.22.0
  react: ^18.3.1
  react-dom: ^18.3.1
  sass: ^1.94.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - msgpackr-extract
  - prisma
