packages:
  - apps/*
  - packages/*
  - infrastructure/*
  - scripts/*

catalog:
  '@prisma/client': ^5.20.0
  concurrently: ^9.0.0
  dotenv: ^16.4.5
  eslint: ^9.0.0
  next: ^14.2.4
  prettier: ^3.3.3
  prisma: ^5.20.0
  react: ^18.3.1
  react-dom: ^18.3.1
  sass: ^1.77.0
  typescript: ^5.6.3

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - msgpackr-extract
  - prisma
